### ISSUE TITLE
K8S master node's api server `:6443` isn't opened

### ISSUE THREAD

**Issue by ghkdqhrbals** [ghkdqhrbals/spring-chatting-server#115]
## **Description**

**Because of low memory resources, kubernetes automatically swapping off api server and other essential components** 😂😂

`scheduler`, `controller-manager`, `api-server` is constantly turned off!!

* Swapped out scheduler and controller-manager

```
ubuntu@ip-172-31-4-229:~$ kubectl get componentstatuses
Warning: v1 ComponentStatus is deprecated in v1.19+
NAME                 STATUS      MESSAGE                                                                                        ERROR
scheduler            Unhealthy   Get "https://127.0.0.1:10259/healthz": dial tcp 127.0.0.1:10259: connect: connection refused   
controller-manager   Unhealthy   Get "https://127.0.0.1:10257/healthz": dial tcp 127.0.0.1:10257: connect: connection refused   
etcd-0               Healthy     ok
```

* Swapped out API server

```
[root@ip-172-31-2-180 ec2-user]# kubectl get csr
The connection to the server 172.31.2.180:6443 was refused - did you specify the right host or port?
```

> ## ~~Solved~~
> 
> We now know that this swapped out process is lack of our server's memory resources. But this things **should be remained in memory**.~~
> 
> * So first we login with root user, turn off `swapoff` option in Linux.~~
> > Swap is space used to swap memory pages to disk when memory is low. Since it is not recommended to use swap on servers running Kubernetes clusters, this command disables swap. The -a option means to disable all currently active swap space.
> 
> * And tracing kuberctl version for constant observing.
> 
> ```
> sudo -i
> swapoff -a
> exit
> strace -eopenat kubectl version
> ```

##  Its Not beacuse of lack of CPU & MEM, rather AWS EC2 linux problems

Since I use OS `Amazon Linux 2023 AMI` and load kubernetes from `Kubernetes package repositories`, it keeps failed. But after using OS `Amazon Linux 2 AMI (HVM) - Kernel 5.10, SSD Volume Type`, loading kubernetes from `Google-hosted package repository`, it works successfully and stable!

**Comment by ghkdqhrbals** [comment]
Additionally, run `cat /proc/swaps` will show nothing if you successfully turn off `swap`

```
[root@ip-172-31-2-180 ec2-user]# cat /proc/swaps
Filename                                Type            Size            Used            Priority
```

**Comment by ghkdqhrbals** [comment]
![Image](https://github.com/ghkdqhrbals/spring-chatting-server/assets/29156882/4fc545f6-a7d9-4187-b0b6-4443bd8599d5)

**Comment by ghkdqhrbals2** [comment]
I found that even if memory swap process is off, maximum of CPU and MEM is fixed. So if kubernetes reach 100% CPU or MEM usage, it turned off...
