### ISSUE TITLE
BeanDefinitionOverrideException

### ISSUE THREAD

**Issue by ghkdqhrbals** [ghkdqhrbals/spring-chatting-server#24]
# Description

When trying to run `user-server` **BeanDefinitionOverrideException** occur.

BeanDefinitionOverrideException in

* **JPA&Redis Repository** 
* **SpringWebSecurity**.

# Solution for this issue
by [mbhave](https://github.com/mbhave)

> https://github.com/spring-projects/spring-boot/issues/26897#issuecomment-861038299 happens because of the explicit @EnableWebfluxSecurity annotation. Without spring.main.web-application-type=reactive, the application is considered to be a spring-mvc application, and the auto-configuration switches on @EnableWebSecurity. The two annotations result in a clash. Setting spring.main.web-application-type=reactive prevents @EnableWebSecurity from being applied which is why it works. Since Spring Boot automatically applies @EnableWebSecurity and @EnableWebFluxSecurity, explicitly adding these is not required. This can be converted to a documentation issue for the spring-hateos limitation as Scott suggested.

https://github.com/spring-projects/spring-boot/issues/26897#issuecomment-870979153

**Comment by TrickAndTrack** [comment]
can you assign this to me would like to work on this!

**Comment by ghkdqhrbals** [comment]
Sure!

But `BeanDefinitionOverrideException` in SpringWebSecurity was already solved by adding `spring.main.web-application-type : reactive` in application.yaml file  in `shop-user-service`.

And `BeanDefinitionOverrideException` in JPA&Redis Repository was also solved by excluding WebMvcAutoConfiguration.class and scanning JPA and RedisRespotory in different path.

Here is the sample code for solving JPA&Redis Repository `BeanDefinitionOverrideException`.

```java
...
@SpringBootApplication(scanBasePackages = "com.example",exclude={DataSourceAutoConfiguration.class,WebMvcAutoConfiguration.class})
@EnableJpaRepositories(basePackages = {"com.example.shopuserservice.domain.user.repository"})
@EnableRedisRepositories(basePackages = {"com.example.shopuserservice.domain.user.redisrepository"})
@EnableDiscoveryClient
@EnableFeignClients
@Import(JpaConfig.class)
@EnableKafka
@EnableWebFlux
public class MainApplication {

	public static void main(String[] args) {
		SpringApplication.run(OrderServiceApplication.class, args);
	}

	@Bean
	public Logger.Level feignLoggerLevel(){
		return Logger.Level.FULL;
	}
	@Bean
	public HttpExchangeRepository httpTraceRepository(){
		return new InMemoryHttpExchangeRepository();
	}

	@Bean(name = "bcrypt")
	PasswordEncoder passwordEncoder() {
		return new BCryptPasswordEncoder();
	}

	@Bean
	public FeignErrorDecoder getFeignErrorDecoder(){
		return new FeignErrorDecoder();
	}


}
```

### Why `BeanDefinitionOverrideException` is occured in SpringWebSecurity?

The main reason I found is that our web security configuration is currently setting as `reactiveSecurity` which is not mvcSecurity. If our server doesn't set any `web-application-type` in application.yaml, Spring automatically set our service as normal mvc pattern to web server and security. 

So spring tries to set it as mvcSecurity, but we want to set it as reactiveSecurity, so it crashes.

To solve this problem, we add `spring.main.web-application-type : reactive` in application.yaml file. And we finally solve `BeanDefinitionOverrideException` occured in SpringWebSecurity.

If you have any questions OR want to contribute this project, please contact!
