### ISSUE TITLE
Rollback interface in authentication server needed

### ISSUE THREAD

**Issue by ghkdqhrbals** [ghkdqhrbals/spring-chatting-server#56]

**Comment by ghkdqhrbals2** [comment]
### **We do not rollback**

Consumptions

* Authentication server sends `user-add` events to chat & customer server. And if some server already has same userId, rollback(removing user) shouldn't be activated, **rather connect to it**.
* To connect with the another server, users need to verify their email. If they cannot verify it, they cannot create accounts in authentication server.
