### ISSUE TITLE
[ERROR] The given id must not be null!

### ISSUE THREAD

**Issue by ghkdqhrbals** [ghkdqhrbals/spring-chatting-server#7]
# Solved

Since I set chatting entity with `generated ID`, chatting.getId() will be null.
I call getId function right before JPA goes through, and of course, chatting has null ID field.

```
Optional<Chatting> findChatting = chatRepository.findById(chatting.getId());
```

**Comment by duykc55** [comment]
How do I fix it?

**Comment by ghkdqhrbals** [comment]
Hi @duykc55. 

Creating a method to check if the id field is null will solve this issue. So we can prevent given id from null issues.

Like,

```java
@Setter
public class Chatting {
    @Id
    @GeneratedValue
    @GeneratedValue(strategy = GenerationType.SEQUENCE)
    private Long id;
    ...
    public Boolean validate(){ // <-- create validation method for prevent from null issue
        return this.id == null
    }
    ...
}
```
